
:let mapleader = ","

:map <leader>w :w <ENTER> 

:map <leader>mk :w <ENTER> :make <ENTER> 

:set textwidth=79
:set colorcolumn=+1

:set nu
:set relativenumber

hi Comment ctermfg=Magenta
hi Search cterm=NONE ctermfg=black ctermbg=cyan

:set hlsearch


